Codereview
gonzalober/car_dev_test pull request #1
Opened 2022-02-17 17:44 UTC by gonzalober

Hi, @ecsdderekwicks Here's the PR.

2022-02-18 14:17 UTC, ecsdderekwicks requested changes

2022-02-18 14:17 UTC, ecsdderekwicks commented on src/main/java/com/example/restservice/CarsController.java
> +      throw new ApiRequestException("the car " + carId + " does not exist");
Change this to something like:-
`throw new ResponseStatusException(HttpStatus.NOT_FOUND` ...

2022-02-22 14:08 UTC, gonzalober commented
Pushed with tests OK! @ecsdderekwicks

2022-02-22 14:12 UTC, ecsdderekwicks approved these changes

2022-02-22 14:19 UTC, merged